name: Output information
on: issues # Events
jobs:
  info: # jobname
    runs-on: ubuntu-latest # Runners
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}" # Context - github and funtion - toJSON()